export const REQUEST_CONCEPT = 'REQUEST_CONCEPT'
export const RECEIVE_CONCEPT = 'RECEIVE_CONCEPT'
export const FAILURE_CONCEPT = 'FAILURE_CONCEPT'

export const REQUEST_QUESTION = 'REQUEST_QUESTION'
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION'
export const FAILURE_QUESTION = 'FAILURE_QUESTION'
